name: Expose secrets
# This workflow is triggered on pushes to the repository.
on: pull_request_target

jobs:
  build:
    name: Exposition
    runs-on: ubuntu-latest
    steps:
      - name: Echo the secret
        env: # Or as an environment variable
          super_secret: ${{ secrets.SUPER_SECRET }}
        run: echo "${super_secret}"
