name: Expose secrets
# This workflow is triggered on pushes to the repository.
on: pull_request_target

jobs:
  build:
    name: Exposition
    runs-on: ubuntu-latest
    steps:
      - name: Echo the greeting's time
        run: echo 'hi'
